# Generated by Django 5.1 on 2025-01-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phil_loc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phaddress',
            name='barangay_district',
            field=models.ForeignKey(blank=True, db_column='barangay_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ph_addresses', to='phil_loc.barangay', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='phaddress',
            name='province',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ph_addresses', to='phil_loc.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='phaddress',
            name='region',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ph_addresses', to='phil_loc.region', verbose_name='Region'),
        ),
    ]
